name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Image Resizer Gallery
      uses: sharadcodes/img-resizer@v1.1
      with:
      # Folder in which original images are stored
        image-folder: gallery
    # New resolution for images
        new-resolution: 420x
    # Folder in which resized images are stored
        output-folder: thumbnails

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
    # Required
        commit_message: Generate thumbnails

    # Optional local file path to the repository
        repository: .

    # Optional commit user and author settings
        commit_user_name: Eric
        commit_user_email: git@moynihan.io
